require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MensagensController do

  # This should return the minimal set of attributes required to create a valid
  # Mensagem. As you add validations to Mensagem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "remetente" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MensagensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mensagens as @mensagens" do
      mensagem = Mensagem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mensagens).should eq([mensagem])
    end
  end

  describe "GET show" do
    it "assigns the requested mensagem as @mensagem" do
      mensagem = Mensagem.create! valid_attributes
      get :show, {:id => mensagem.to_param}, valid_session
      assigns(:mensagem).should eq(mensagem)
    end
  end

  describe "GET new" do
    it "assigns a new mensagem as @mensagem" do
      get :new, {}, valid_session
      assigns(:mensagem).should be_a_new(Mensagem)
    end
  end

  describe "GET edit" do
    it "assigns the requested mensagem as @mensagem" do
      mensagem = Mensagem.create! valid_attributes
      get :edit, {:id => mensagem.to_param}, valid_session
      assigns(:mensagem).should eq(mensagem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mensagem" do
        expect {
          post :create, {:mensagem => valid_attributes}, valid_session
        }.to change(Mensagem, :count).by(1)
      end

      it "assigns a newly created mensagem as @mensagem" do
        post :create, {:mensagem => valid_attributes}, valid_session
        assigns(:mensagem).should be_a(Mensagem)
        assigns(:mensagem).should be_persisted
      end

      it "redirects to the created mensagem" do
        post :create, {:mensagem => valid_attributes}, valid_session
        response.should redirect_to(Mensagem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mensagem as @mensagem" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mensagem.any_instance.stub(:save).and_return(false)
        post :create, {:mensagem => { "remetente" => "invalid value" }}, valid_session
        assigns(:mensagem).should be_a_new(Mensagem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mensagem.any_instance.stub(:save).and_return(false)
        post :create, {:mensagem => { "remetente" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mensagem" do
        mensagem = Mensagem.create! valid_attributes
        # Assuming there are no other mensagens in the database, this
        # specifies that the Mensagem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mensagem.any_instance.should_receive(:update).with({ "remetente" => "MyString" })
        put :update, {:id => mensagem.to_param, :mensagem => { "remetente" => "MyString" }}, valid_session
      end

      it "assigns the requested mensagem as @mensagem" do
        mensagem = Mensagem.create! valid_attributes
        put :update, {:id => mensagem.to_param, :mensagem => valid_attributes}, valid_session
        assigns(:mensagem).should eq(mensagem)
      end

      it "redirects to the mensagem" do
        mensagem = Mensagem.create! valid_attributes
        put :update, {:id => mensagem.to_param, :mensagem => valid_attributes}, valid_session
        response.should redirect_to(mensagem)
      end
    end

    describe "with invalid params" do
      it "assigns the mensagem as @mensagem" do
        mensagem = Mensagem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mensagem.any_instance.stub(:save).and_return(false)
        put :update, {:id => mensagem.to_param, :mensagem => { "remetente" => "invalid value" }}, valid_session
        assigns(:mensagem).should eq(mensagem)
      end

      it "re-renders the 'edit' template" do
        mensagem = Mensagem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mensagem.any_instance.stub(:save).and_return(false)
        put :update, {:id => mensagem.to_param, :mensagem => { "remetente" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mensagem" do
      mensagem = Mensagem.create! valid_attributes
      expect {
        delete :destroy, {:id => mensagem.to_param}, valid_session
      }.to change(Mensagem, :count).by(-1)
    end

    it "redirects to the mensagens list" do
      mensagem = Mensagem.create! valid_attributes
      delete :destroy, {:id => mensagem.to_param}, valid_session
      response.should redirect_to(mensagens_url)
    end
  end

end
